{
  "location" : "scorn_riverside",
  "rules": [
  {
  "match" : ["name"],
  "pre" : [],
  "post" : [],
  "msg" : ["Name's Jacey. Nice to meet you."]
  }, {
  "match" : ["eswald", "coffee"],
  "pre" : [["quest", "scorn/CoffeeGoose", "10-90"]],
  "post" : [],
  "msg" : ["Yeah! Eswald used to have the BEST coffee around. I wish I knew what happened."]
  }, {
  "match" : ["cards", "gamble", "gambling"],
  "pre" : [],
  "post" : [],
  "msg" : ["Best cards and gambling in all of Scorn is over at Goth's Tavern."]
  }, {
  "match" : ["mark"],
  "pre" : [],
  "post" : [],
  "msg" : ["Ya good guy lets me beat him at cards all the time. Guy loves to gamble. Otherwise he's a bum."]
  }, {
  "match" : ["esmeralda"],
  "pre" : [],
  "post" : [],
  "msg" : ["I don't know who that is, sorry."]
  }, {
  "match" : ["goose"],
  "pre" : [],
  "post" : [],
  "msg" : ["I suppose the bird making all those sounds could be a goose. It sounds close!"]
  }, {
  "match" : ["bird", "sounds", "honk", "hear"],
  "pre" : [],
  "post" : [],
  "msg" : ["Ya! Don't ya hear that bird nearby?! HONK HONK!"]
  }, {
  "match" : ["amy"],
  "pre" : [],
  "post" : [],
  "msg" : ["She runs the place for that rat Witherspoon."]
  }, {
  "match" : ["Witherspoon", "landlord", "rat"],
  "pre" : [],
  "post" : [],
  "msg" : ["Witherspoon owns all these slums... err, 'condos'."]
  }, {
  "match" : ["gramps", "malone", "staff", "stick"],
  "pre" : [["quest", "scorn/WalkingStick", "40"]],
  "post" : [],
  "msg" : ["Ya ol Gramps Malone is right duffer.\nPlays a good game of orc knuckles.\nI think he left his walking stick here last time he came round.\nThink it's under the table..."]
  }, {
  "match" : ["gramps", "malone", "staff", "stick"],
  "pre" : [["quest", "scorn/WalkingStick", "20-30"]],
  "post" : [["quest", "scorn/WalkingStick", "40"]],
  "msg" : ["Ya ol Gramps Malone is right duffer.\nPlays a good game of orc knuckles.\nI think he left his walking stick here last time he came round.\nThink it's under the table..."]
  }, {
  "match" : ["gramps", "malone", "staff", "stick"],
  "pre" : [],
  "post" : [],
  "msg" : ["Ya ol Gramps Malone is right duffer.\nPlays a good game of orc knuckles.\nI think he left his walking stick here last time he came round.\nThink it's under the table..."]
  }, {
  "match" : ["*"],
  "pre" : [],
  "post" : [],
  "msg" : ["Darn bird keeps me awake all night..."]
  }
]}
