{
  "location" : "shrine1",
  "rules": [
  {
  "match" : ["yes"],
  "pre" : [],
  "post" : [["quest", "quests/JadeChest", "10"]],
  "msg" : ["In searching for information on the Jade Chest our informant in Navar seems to have found some valuable knowledge. The eastern wind gives you the duty to investigate this finding."]
  },
  {
  "match" : ["*"],
  "pre" : [],
  "post" : [],
  "msg" : ["There is much work to be done in unlocking the secrets of the Jade Chest. Azumauindo's interests lie within its grasp. Will you fulfill your duty?"]
  }
]}
